# bin2c.py
# 功能：读取任意 .bin 文件，并生成 C 语言数组
# 使用方法：python bin2c.py spi_bridge.bin spi_bridge_bin.h

import sys

def bin2c(input_bin_path, output_c_path, array_name="g_spi_bridge_bin"):
    # 读取二进制文件
    with open(input_bin_path, "rb") as f:
        data = f.read()

    # 生成 C 数组格式
    lines = []
    for i in range(0, len(data), 16):
        line_data = data[i:i+16]
        line = "    " + ", ".join(f"0x{b:02X}" for b in line_data) + ","
        lines.append(line)

    array_len = len(data)

    # 写入 .h 文件
    with open(output_c_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by bin2c.py\n")
        f.write("// DO NOT EDIT manually\n\n")
        f.write("#ifndef __SPI_BRIDGE_BIN_H\n")
        f.write("#define __SPI_BRIDGE_BIN_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"const uint8_t {array_name}[] = {{\n")
        f.write("\n".join(lines) + "\n")
        f.write("};\n\n")
        f.write(f"const uint32_t {array_name}_len = {array_len};\n\n")
        f.write("#endif\n")

    print(f"成功生成：{output_c_path}")
    print(f"文件大小：{array_len} 字节")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python bin2c.py input.bin output.h")
        print("Example: python bin2c.py spi_bridge.bin spi_bridge_bin.h")
        sys.exit(1)

    input_bin = sys.argv[1]
    output_c = sys.argv[2]

    bin2c(input_bin, output_c)