set_property SRC_FILE_INFO {cfile:D:/CubeMX/STM32H743_XC7A100_PS_Configuration/Mouse_Key/constrs_1/mouse_key_spi_bridge.xdc rfile:../../../constrs_1/mouse_key_spi_bridge.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E21 [get_ports ch9350_txd]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports spi_cs_data]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports spi_sdo]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports spi_cs_cmd]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports spi_scl]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports spi_sdi]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_spi_comm/u_spi/u_spi_cmd_data/u_spi_data_channel/spi_cs_reg[0]} {u_spi_comm/u_spi/u_spi_cmd_data/u_spi_data_channel/spi_cs_reg[1]} {u_spi_comm/u_spi/u_spi_cmd_data/u_spi_data_channel/spi_cs_reg[2]}]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_spi_comm/u_spi/u_spi_cmd_data/cs_cmd_sync[0]} {u_spi_comm/u_spi/u_spi_cmd_data/cs_cmd_sync[1]} {u_spi_comm/u_spi/u_spi_cmd_data/cs_cmd_sync[2]}]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_spi_comm/u_spi/u_spi_cmd_data/curr_ch_addr[0]} {u_spi_comm/u_spi/u_spi_cmd_data/curr_ch_addr[1]} {u_spi_comm/u_spi/u_spi_cmd_data/curr_ch_addr[2]} {u_spi_comm/u_spi/u_spi_cmd_data/curr_ch_addr[3]}]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_spi_comm/u_spi/u_spi_cmd_data/cmd_addr[0]} {u_spi_comm/u_spi/u_spi_cmd_data/cmd_addr[1]} {u_spi_comm/u_spi/u_spi_cmd_data/cmd_addr[2]} {u_spi_comm/u_spi/u_spi_cmd_data/cmd_addr[3]} {u_spi_comm/u_spi/u_spi_cmd_data/cmd_addr[4]} {u_spi_comm/u_spi/u_spi_cmd_data/cmd_addr[5]} {u_spi_comm/u_spi/u_spi_cmd_data/cmd_addr[6]} {u_spi_comm/u_spi/u_spi_cmd_data/cmd_addr[7]}]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[0]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[1]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[2]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[3]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[4]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[5]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[6]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[7]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[8]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[9]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[10]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[11]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[12]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[13]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[14]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[15]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[16]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[17]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[18]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[19]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[20]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[21]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[22]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[23]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[24]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[25]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[26]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[27]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[28]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[29]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[30]} {u_spi_comm/u_spi/u_spi_cmd_data/rx_data[31]}]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[0]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[1]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[2]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[3]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[4]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[5]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[6]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[7]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[8]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[9]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[10]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[11]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[12]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[13]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[14]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[15]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[16]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[17]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[18]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[19]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[20]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[21]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[22]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[23]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[24]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[25]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[26]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[27]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[28]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[29]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[30]} {u_spi_comm/u_spi/u_spi_cmd_data/tx_data[31]}]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_spi_comm/write_reg_2[0]} {u_spi_comm/write_reg_2[1]} {u_spi_comm/write_reg_2[2]} {u_spi_comm/write_reg_2[3]} {u_spi_comm/write_reg_2[4]} {u_spi_comm/write_reg_2[5]} {u_spi_comm/write_reg_2[6]} {u_spi_comm/write_reg_2[7]} {u_spi_comm/write_reg_2[8]} {u_spi_comm/write_reg_2[9]} {u_spi_comm/write_reg_2[10]} {u_spi_comm/write_reg_2[11]} {u_spi_comm/write_reg_2[12]} {u_spi_comm/write_reg_2[13]} {u_spi_comm/write_reg_2[14]} {u_spi_comm/write_reg_2[15]} {u_spi_comm/write_reg_2[16]} {u_spi_comm/write_reg_2[17]} {u_spi_comm/write_reg_2[18]} {u_spi_comm/write_reg_2[19]} {u_spi_comm/write_reg_2[20]} {u_spi_comm/write_reg_2[21]} {u_spi_comm/write_reg_2[22]} {u_spi_comm/write_reg_2[23]} {u_spi_comm/write_reg_2[24]} {u_spi_comm/write_reg_2[25]} {u_spi_comm/write_reg_2[26]} {u_spi_comm/write_reg_2[27]} {u_spi_comm/write_reg_2[28]} {u_spi_comm/write_reg_2[29]} {u_spi_comm/write_reg_2[30]} {u_spi_comm/write_reg_2[31]}]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {reg_data1[0]} {reg_data1[1]} {reg_data1[2]} {reg_data1[3]} {reg_data1[4]} {reg_data1[5]} {reg_data1[6]} {reg_data1[7]} {reg_data1[8]} {reg_data1[9]} {reg_data1[10]} {reg_data1[11]} {reg_data1[12]} {reg_data1[13]} {reg_data1[14]} {reg_data1[15]} {reg_data1[16]} {reg_data1[17]} {reg_data1[18]} {reg_data1[19]} {reg_data1[20]} {reg_data1[21]} {reg_data1[22]} {reg_data1[23]} {reg_data1[24]} {reg_data1[25]} {reg_data1[26]} {reg_data1[27]} {reg_data1[28]} {reg_data1[29]} {reg_data1[30]} {reg_data1[31]}]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_spi_comm/write_reg_0[0]} {u_spi_comm/write_reg_0[1]} {u_spi_comm/write_reg_0[2]} {u_spi_comm/write_reg_0[3]} {u_spi_comm/write_reg_0[4]} {u_spi_comm/write_reg_0[5]} {u_spi_comm/write_reg_0[6]} {u_spi_comm/write_reg_0[7]} {u_spi_comm/write_reg_0[8]} {u_spi_comm/write_reg_0[9]} {u_spi_comm/write_reg_0[10]} {u_spi_comm/write_reg_0[11]} {u_spi_comm/write_reg_0[12]} {u_spi_comm/write_reg_0[13]} {u_spi_comm/write_reg_0[14]} {u_spi_comm/write_reg_0[15]} {u_spi_comm/write_reg_0[16]} {u_spi_comm/write_reg_0[17]} {u_spi_comm/write_reg_0[18]} {u_spi_comm/write_reg_0[19]} {u_spi_comm/write_reg_0[20]} {u_spi_comm/write_reg_0[21]} {u_spi_comm/write_reg_0[22]} {u_spi_comm/write_reg_0[23]} {u_spi_comm/write_reg_0[24]} {u_spi_comm/write_reg_0[25]} {u_spi_comm/write_reg_0[26]} {u_spi_comm/write_reg_0[27]} {u_spi_comm/write_reg_0[28]} {u_spi_comm/write_reg_0[29]} {u_spi_comm/write_reg_0[30]} {u_spi_comm/write_reg_0[31]}]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {reg_data2[0]} {reg_data2[1]} {reg_data2[2]} {reg_data2[3]} {reg_data2[4]} {reg_data2[5]} {reg_data2[6]} {reg_data2[7]} {reg_data2[8]} {reg_data2[9]} {reg_data2[10]} {reg_data2[11]} {reg_data2[12]} {reg_data2[13]} {reg_data2[14]} {reg_data2[15]} {reg_data2[16]} {reg_data2[17]} {reg_data2[18]} {reg_data2[19]} {reg_data2[20]} {reg_data2[21]} {reg_data2[22]} {reg_data2[23]} {reg_data2[24]} {reg_data2[25]} {reg_data2[26]} {reg_data2[27]} {reg_data2[28]} {reg_data2[29]} {reg_data2[30]} {reg_data2[31]}]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {uart_byte[0]} {uart_byte[1]} {uart_byte[2]} {uart_byte[3]} {uart_byte[4]} {uart_byte[5]} {uart_byte[6]} {uart_byte[7]}]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {reg_data0[0]} {reg_data0[1]} {reg_data0[2]} {reg_data0[3]} {reg_data0[4]} {reg_data0[5]} {reg_data0[6]} {reg_data0[7]} {reg_data0[8]} {reg_data0[9]} {reg_data0[10]} {reg_data0[11]} {reg_data0[12]} {reg_data0[13]} {reg_data0[14]} {reg_data0[15]} {reg_data0[16]} {reg_data0[17]} {reg_data0[18]} {reg_data0[19]} {reg_data0[20]} {reg_data0[21]} {reg_data0[22]} {reg_data0[23]} {reg_data0[24]} {reg_data0[25]} {reg_data0[26]} {reg_data0[27]} {reg_data0[28]} {reg_data0[29]} {reg_data0[30]} {reg_data0[31]}]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {u_spi_comm/write_reg_1[0]} {u_spi_comm/write_reg_1[1]} {u_spi_comm/write_reg_1[2]} {u_spi_comm/write_reg_1[3]} {u_spi_comm/write_reg_1[4]} {u_spi_comm/write_reg_1[5]} {u_spi_comm/write_reg_1[6]} {u_spi_comm/write_reg_1[7]} {u_spi_comm/write_reg_1[8]} {u_spi_comm/write_reg_1[9]} {u_spi_comm/write_reg_1[10]} {u_spi_comm/write_reg_1[11]} {u_spi_comm/write_reg_1[12]} {u_spi_comm/write_reg_1[13]} {u_spi_comm/write_reg_1[14]} {u_spi_comm/write_reg_1[15]} {u_spi_comm/write_reg_1[16]} {u_spi_comm/write_reg_1[17]} {u_spi_comm/write_reg_1[18]} {u_spi_comm/write_reg_1[19]} {u_spi_comm/write_reg_1[20]} {u_spi_comm/write_reg_1[21]} {u_spi_comm/write_reg_1[22]} {u_spi_comm/write_reg_1[23]} {u_spi_comm/write_reg_1[24]} {u_spi_comm/write_reg_1[25]} {u_spi_comm/write_reg_1[26]} {u_spi_comm/write_reg_1[27]} {u_spi_comm/write_reg_1[28]} {u_spi_comm/write_reg_1[29]} {u_spi_comm/write_reg_1[30]} {u_spi_comm/write_reg_1[31]}]]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list u_spi_comm/ch9350_frame_valid_d1]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list kb_mouse_valid]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list u_spi_comm/reg1_sent]]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {u_spi_comm/u_spi/u_spi_cmd_data/u_spi_data_channel/Shift_Reg_Din[31]_i_1_n_0}]]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {u_spi_comm/u_spi/u_spi_cmd_data/u_spi_data_channel/Shift_Reg_DOUT[31]_i_1_n_0}]]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list u_spi_comm/u_spi/u_spi_cmd_data/u_spi_data_channel/spi_cs_neg_flag]]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list u_spi_comm/u_spi/u_spi_cmd_data/u_spi_data_channel/spi_cs_pos_flag]]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list u_spi_comm/u_spi/u_spi_cmd_data/u_spi_data_channel/spi_scl_neg_flag]]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list u_spi_comm/u_spi/u_spi_cmd_data/u_spi_data_channel/spi_scl_pos_flag]]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list u_spi_comm/wheel_cleared]]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
